import mongoose from 'mongoose';
import dns from 'dns';
import dotenv from 'dotenv';
import Station from './models/Station.js';
import Node from './models/Node.js';
import Edge from './models/Edge.js';

dotenv.config();

// Ensure public DNS resolver is used for MongoDB SRV records on Windows networks
dns.setServers(['8.8.8.8', '8.8.4.4', '1.1.1.1']);

const stationsData = [
  {
    stationId: 'MAS',
    name: 'Puratchi Thalaivar Dr. M.G. Ramachandran Central',
    nameTa: 'புரட்சித் தலைவர் டாக்டர் எம்.ஜி.ஆர் மத்திய ரயில் நிலையம் (சென்னை சென்ட்ரல்)',
    nameHi: 'पुरातची तलैवर डॉ. एम.जी. रामचंद्रन सेंट्रल (चेन्नई सेंट्रल)',
    city: 'Chennai',
    canvasWidth: 800,
    canvasHeight: 600,
  },
  {
    stationId: 'MS',
    name: 'Chennai Egmore',
    nameTa: 'சென்னை எழும்பூர் ரயில் நிலையம்',
    nameHi: 'चेन्नई एग्मोर रेलवे स्टेशन',
    city: 'Chennai',
    canvasWidth: 800,
    canvasHeight: 600,
  },
  {
    stationId: 'TBM',
    name: 'Tambaram',
    nameTa: 'தாம்பரம் ரயில் நிலையம்',
    nameHi: 'तांबरम रेलवे स्टेशन',
    city: 'Chennai',
    canvasWidth: 800,
    canvasHeight: 600,
  },
];

const nodesData = [
  // =========================================================================
  // Station 1: MAS (Puratchi Thalaivar Dr. M.G.R. Central)
  // Platforms 1 to 12 with Buffer Concourse & Central FOB
  // =========================================================================
  {
    stationId: 'MAS',
    nodeId: 'MAS_MAIN_GATE',
    name: 'Main Portico Entrance (EVR Periyar Salai)',
    nameTa: 'பிரதான நுழைவு வாயில் (ஈ.வெ.ரா பெரியார் சாலை)',
    nameHi: 'मुख्य पोर्टिको प्रवेश द्वार (EVR पेरियार सलाई)',
    type: 'gate',
    floor: 'Ground',
    x: 100,
    y: 520,
    isAccessible: true,
    description: 'Main heritage clocktower entrance facing Poonamallee High Road / EVR Salai',
    descriptionTa: 'பூந்தமல்லி நெடுஞ்சாலை நோக்கிய பிரதான பாரம்பரிய நுழைவு வாயில்',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_MMC_GATE',
    name: 'Moore Market Complex (Suburban) Gate',
    nameTa: 'மூர் மார்க்கெட் புறநகர் ரயில் நுழைவு வாயில்',
    nameHi: 'मूर मार्केट कॉम्प्लेक्स (उपनगरीय) गेट',
    type: 'gate',
    floor: 'Ground',
    x: 80,
    y: 200,
    isAccessible: true,
    description: 'Suburban terminal entrance connecting MMC to main station building',
    descriptionTa: 'மூர் மார்க்கெட் புறநகர் முனையத்தை இணைக்கும் நுழைவு வாயில்',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_CONCOURSE',
    name: 'Grand Concourse & Buffer Stops',
    nameTa: 'மத்திய பயணிகள் அரங்கம் & பஃபர் ஸ்டாப்',
    nameHi: 'भव्य कॉनकोर्स एवं बफर स्टॉप्स',
    type: 'hall',
    floor: 'Ground',
    x: 240,
    y: 420,
    isAccessible: true,
    description: 'Grand central concourse walkway accessing all terminal platform buffers',
    descriptionTa: 'அனைத்து நடைமேடைகளையும் இணைக்கும் அகலமான தரைதள அரங்கம்',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_DIVYANG',
    name: 'Divyangjan Buggy & Wheelchair Booth',
    nameTa: 'மாற்றுத்திறனாளிகள் உதவி மையம் & பேட்டரி கார்',
    nameHi: 'दिव्यांगजन सहायता एवं बैटरी बग्गी बूथ',
    type: 'helpdesk',
    floor: 'Ground',
    x: 190,
    y: 440,
    isAccessible: true,
    description: 'Dedicated Divyangjan kiosk offering wheelchairs and electric transfer buggies',
    descriptionTa: 'சக்கர நாற்காலிகள் மற்றும் மின்கல வாகன உதவி மையம்',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_FOB_LIFT_MAIN',
    name: 'Central FOB Lift A',
    nameTa: 'மத்திய நடைமேம்பால மின்தூக்கி A',
    nameHi: 'सेंट्रल एफओबी लिफ्ट A',
    type: 'lift',
    floor: 'Ground',
    x: 340,
    y: 360,
    isAccessible: true,
    description: 'Ground level high-capacity elevator ascending to Central Foot Overbridge',
    descriptionTa: 'தரைதளத்திலிருந்து மத்திய நடைமேம்பாலத்திற்கு செல்லும் மின்தூக்கி',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_FOB_STAIRS_MAIN',
    name: 'Central FOB Concourse Stairs',
    nameTa: 'மத்திய நடைமேம்பால படிக்கட்டுகள்',
    nameHi: 'सेंट्रल एफओबी कॉनकोर्स सीढ़ियाँ',
    type: 'stairs',
    floor: 'Ground',
    x: 340,
    y: 430,
    isAccessible: false,
    description: 'Wide flight staircase ascending from concourse to Foot Overbridge',
    descriptionTa: 'அரங்கத்திலிருந்து நடைமேம்பாலத்திற்கு செல்லும் படிக்கட்டுகள்',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_FOB_DECK',
    name: 'Central Overbridge Deck (Level 1)',
    nameTa: 'மத்திய நடைமேம்பால தளம் (முதல் தளம்)',
    nameHi: 'सेंट्रल ओवरब्रिज डेक (लेवल 1)',
    type: 'fob',
    floor: 'Level 1',
    x: 480,
    y: 360,
    isAccessible: true,
    description: 'Elevated walkway deck spanning across platforms with lift bays',
    descriptionTa: 'நடைமேடைகளை கடக்கும் உயரமான நடைமேம்பால பாதை',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_P1',
    name: 'Platform 1 (Direct Concourse Access)',
    nameTa: 'நடைமேடை 1 (நேரடி தரைதள வழி)',
    nameHi: 'प्लेटफॉर्म 1 (प्रत्यक्ष कॉनकोर्स प्रवेश)',
    type: 'platform',
    floor: 'Ground',
    x: 400,
    y: 480,
    isAccessible: true,
    description: 'Premium terminal platform 1 with level step-free walk directly from main portico',
    descriptionTa: 'பிரதான நுழைவிலிருந்து படி இல்லாத நேரடி நடைமேடை 1',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_P2_LIFT',
    name: 'Platform 2 FOB Lift',
    nameTa: 'நடைமேடை 2 நடைமேம்பால மின்தூக்கி',
    nameHi: 'प्लेटफॉर्म 2 एफओबी लिफ्ट',
    type: 'lift',
    floor: 'Level 1',
    x: 480,
    y: 310,
    isAccessible: true,
    description: 'Elevator providing step-free descent from FOB deck down to Platform 2',
    descriptionTa: 'நடைமேம்பாலத்திலிருந்து நடைமேடை 2-க்கு இறங்கும் மின்தூக்கி',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_P2',
    name: 'Platform 2 Boarding Deck',
    nameTa: 'நடைமேடை 2 ஏறும் தளம்',
    nameHi: 'प्लेटफॉर्म 2 बोर्डिंग डेक',
    type: 'platform',
    floor: 'Ground',
    x: 480,
    y: 440,
    isAccessible: true,
    description: 'Mainline platform 2 serving express trains to Bengaluru and Coimbatore',
    descriptionTa: 'பெங்களூரு மற்றும் கோவை விரைவு ரயில்களுக்கான நடைமேடை 2',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_P3_4',
    name: 'Platform 3 & 4 Mainline Island',
    nameTa: 'நடைமேடை 3 & 4 விரைவு ரயில் தளம்',
    nameHi: 'प्लेटफॉर्म 3 एवं 4 मेनलाइन आइलैंड',
    type: 'platform',
    floor: 'Ground',
    x: 560,
    y: 440,
    isAccessible: true,
    description: 'Island boarding deck for Platforms 3 & 4 intercity expresses',
    descriptionTa: 'விரைவு ரயில்களுக்கான நடைமேடை 3 & 4',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_P5_6',
    name: 'Platform 5 & 6 Mainline Island',
    nameTa: 'நடைமேடை 5 & 6 விரைவு ரயில் தளம்',
    nameHi: 'प्लेटफॉर्म 5 एवं 6 मेनलाइन आइलैंड',
    type: 'platform',
    floor: 'Ground',
    x: 640,
    y: 440,
    isAccessible: true,
    description: 'Island boarding deck for Platforms 5 & 6 superfast trains',
    descriptionTa: 'அதிவிரைவு ரயில்களுக்கான நடைமேடை 5 & 6',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_P7_8',
    name: 'Platform 7 & 8 Express Deck',
    nameTa: 'நடைமேடை 7 & 8 விரைவு ரயில் தளம்',
    nameHi: 'प्लेटफॉर्म 7 एवं 8 एक्सप्रेस डेक',
    type: 'platform',
    floor: 'Ground',
    x: 720,
    y: 440,
    isAccessible: true,
    description: 'Island boarding deck for Platforms 7 & 8 long-distance services',
    descriptionTa: 'நீண்ட தூர ரயில்களுக்கான நடைமேடை 7 & 8',
  },
  {
    stationId: 'MAS',
    nodeId: 'MAS_P9_12',
    name: 'Platforms 9 to 12 Northern Express Bay',
    nameTa: 'நடைமேடைகள் 9 முதல் 12 வட இந்திய விரைவு ரயில் பகுதி',
    nameHi: 'प्लेटफॉर्म 9 से 12 उत्तरी एक्सप्रेस बे',
    type: 'platform',
    floor: 'Ground',
    x: 770,
    y: 380,
    isAccessible: true,
    description: 'Terminal bay for Platforms 9 through 12 serving North & East bound express trains',
    descriptionTa: 'வடக்கு மற்றும் கிழக்கு நோக்கி செல்லும் ரயில்களுக்கான நடைமேடைகள் 9 முதல் 12',
  },

  // =========================================================================
  // Station 2: MS (Chennai Egmore)
  // All 11 Platforms with Subway & Concourse Integration
  // =========================================================================
  {
    stationId: 'MS',
    nodeId: 'MS_GATE_1',
    name: 'Gandhi Irwin Road Main Entrance (East)',
    nameTa: 'காந்தி இர்வின் சாலை பிரதான நுழைவு வாயில் (கிழக்கு)',
    nameHi: 'गांधी इरविन रोड मुख्य प्रवेश द्वार (पूर्व)',
    type: 'gate',
    floor: 'Ground',
    x: 90,
    y: 480,
    isAccessible: true,
    description: 'Main eastern entrance facing Gandhi Irwin Road and auto/taxi rank',
    descriptionTa: 'காந்தி இர்வின் சாலையை நோக்கிய கிழக்கு பிரதான நுழைவு வாயில்',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_GATE_2',
    name: 'EVK Sampath Road Entrance (West)',
    nameTa: 'ஈ.வெ.கி சம்பத் சாலை நுழைவு வாயில் (மேற்கு)',
    nameHi: 'ईवीके संपत रोड प्रवेश द्वार (पश्चिम)',
    type: 'gate',
    floor: 'Ground',
    x: 720,
    y: 200,
    isAccessible: true,
    description: 'Western entrance giving direct terminal access to Platforms 10 & 11',
    descriptionTa: 'நடைமேடைகள் 10 & 11 பகுதிக்கு செல்லும் மேற்கு நுழைவு வாயில்',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_MAIN_HALL',
    name: 'Main Heritage Booking Concourse',
    nameTa: 'பாரம்பரிய முன்பதிவு மற்றும் டிக்கெட் அரங்கம்',
    nameHi: 'मुख्य हेरिटेज बुकिंग कॉनकोर्स',
    type: 'hall',
    floor: 'Ground',
    x: 200,
    y: 450,
    isAccessible: true,
    description: 'Historical main concourse with PRS ticket counters and direct platform access',
    descriptionTa: 'வரலாற்று சிறப்புமிக்க முன்பதிவு மையம் மற்றும் டிக்கெட் அரங்கம்',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_DIVYANG_DESK',
    name: 'Divyangjan Special Assistance Booth',
    nameTa: 'மாற்றுத்திறனாளிகள் சிறப்பு உதவி மையம்',
    nameHi: 'दिव्यांगजन विशेष सहायता केंद्र',
    type: 'helpdesk',
    floor: 'Ground',
    x: 180,
    y: 510,
    isAccessible: true,
    description: 'Special accessibility helpdesk for wheelchair requests and porter assistance',
    descriptionTa: 'சக்கர நாற்காலி உதவி மற்றும் வழிகாட்டுதல் மையம்',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_P1',
    name: 'Platform 1 (Ground Level Concourse Access)',
    nameTa: 'நடைமேடை 1 (நேரடி தரைதள வழி)',
    nameHi: 'प्लेटफॉर्म 1 (भू-तल कॉनकोर्स प्रवेश)',
    type: 'platform',
    floor: 'Ground',
    x: 260,
    y: 480,
    isAccessible: true,
    description: 'Zero-step accessible platform 1 running continuous with main station hall',
    descriptionTa: 'பிரதான அரங்கத்திற்கு நேரடி தரைதள வழியுள்ள நடைமேடை 1',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_SUB_RAMP_P1',
    name: 'Subway Ramp P1',
    nameTa: 'நடைமேடை 1 சுரங்க சாய்வுதளப் பாதை',
    nameHi: 'सबवे रैंप P1',
    type: 'ramp',
    floor: 'Subway',
    x: 240,
    y: 380,
    isAccessible: true,
    description: 'Gentle step-free incline ramp descending from Platform 1 to Central Subway Tunnel',
    descriptionTa: 'நடைமேடை 1-லிருந்து சுரங்கப்பாதைக்கு செல்லும் சாய்வுதளம்',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_SUB_STAIR_P1',
    name: 'Subway Stairs P1',
    nameTa: 'நடைமேடை 1 சுரங்க படிக்கட்டுகள்',
    nameHi: 'सबवे सीढ़ियाँ P1',
    type: 'stairs',
    floor: 'Subway',
    x: 280,
    y: 380,
    isAccessible: false,
    description: 'Flight staircase descending to subway tunnel from Platform 1',
    descriptionTa: 'நடைமேடை 1-லிருந்து சுரங்கப்பாதைக்கு இறங்கும் படிக்கட்டுகள்',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_SUB_TUNNEL_A',
    name: 'Subway Central Arterial Tunnel',
    nameTa: 'மத்திய சுரங்க நடைபாதை தடம்',
    nameHi: 'सबवे सेंट्रल मुख्य सुरंग',
    type: 'hall',
    floor: 'Subway',
    x: 400,
    y: 350,
    isAccessible: true,
    description: 'Main underground arterial tunnel connecting all platforms with gentle ramps',
    descriptionTa: 'அனைத்து நடைமேடைகளுக்கும் செல்லும் பிரதான சுரங்க நடைபாதை',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_P2_3',
    name: 'Platform 2 & 3 Island Deck',
    nameTa: 'நடைமேடை 2 & 3 விரைவு ரயில் தளம்',
    nameHi: 'प्लेटफॉर्म 2 एवं 3 आइलैंड डेक',
    type: 'platform',
    floor: 'Ground',
    x: 350,
    y: 480,
    isAccessible: true,
    description: 'Island platform 2 & 3 connecting to southern express train services',
    descriptionTa: 'தென்மாவட்ட விரைவு ரயில்களுக்கான நடைமேடை 2 & 3',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_SUB_RAMP_P4',
    name: 'Subway Ramp PF 4/5',
    nameTa: 'நடைமேடை 4/5 சுரங்க சாய்வுதளம்',
    nameHi: 'सबवे रैंप PF 4/5',
    type: 'ramp',
    floor: 'Subway',
    x: 420,
    y: 380,
    isAccessible: true,
    description: 'Step-free ramp leading up from subway tunnel to Platform 4 & 5',
    descriptionTa: 'சுரங்கப்பாதையிலிருந்து நடைமேடை 4 & 5-க்கு செல்லும் சாய்வுதளம்',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_SUB_STAIR_P4',
    name: 'Subway Stairs PF 4/5',
    nameTa: 'நடைமேடை 4/5 சுரங்க படிக்கட்டுகள்',
    nameHi: 'सबवे सीढ़ियाँ PF 4/5',
    type: 'stairs',
    floor: 'Subway',
    x: 460,
    y: 380,
    isAccessible: false,
    description: 'Stairs ascending to Platforms 4 & 5 from the central subway',
    descriptionTa: 'சுரங்கப்பாதையிலிருந்து நடைமேடை 4 & 5-க்கு செல்லும் படிக்கட்டுகள்',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_P4_5',
    name: 'Platform 4 & 5 (Express Line)',
    nameTa: 'நடைமேடை 4 & 5 (விரைவு ரயில் தளம்)',
    nameHi: 'प्लेटफॉर्म 4 एवं 5 (एक्सप्रेस लाइन)',
    type: 'platform',
    floor: 'Ground',
    x: 440,
    y: 480,
    isAccessible: true,
    description: 'Central express island deck for Kanyakumari and Madurai trains',
    descriptionTa: 'கன்னியாகுமரி மற்றும் மதுரை ரயில்களுக்கான நடைமேடை 4 & 5',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_P6_7',
    name: 'Platform 6 & 7 (Southern Express)',
    nameTa: 'நடைமேடை 6 & 7 (தெற்கு விரைவு ரயில் தளம்)',
    nameHi: 'प्लेटफॉर्म 6 एवं 7 (दक्षिणी एक्सप्रेस)',
    type: 'platform',
    floor: 'Ground',
    x: 530,
    y: 480,
    isAccessible: true,
    description: 'Long-distance express platform connected via subway ramp',
    descriptionTa: 'சுரங்கப்பாதை சாய்வுதளம் வழியான நடைமேடை 6 & 7',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_P8_9',
    name: 'Platform 8 & 9 (Suburban Line)',
    nameTa: 'நடைமேடை 8 & 9 (மின்சார புறநகர் தளம்)',
    nameHi: 'प्लेटफॉर्म 8 एवं 9 (उपनगरीय लाइन)',
    type: 'platform',
    floor: 'Ground',
    x: 620,
    y: 480,
    isAccessible: true,
    description: 'Chennai Beach - Tambaram EMU suburban line island platform',
    descriptionTa: 'தாம்பரம் - சென்னை கடற்கரை மின்சார ரயில்களுக்கான நடைமேடை 8 & 9',
  },
  {
    stationId: 'MS',
    nodeId: 'MS_P10_11',
    name: 'Platform 10 & 11 (West Terminal Deck)',
    nameTa: 'நடைமேடை 10 & 11 (மேற்கு முனைய தளம்)',
    nameHi: 'प्लेटफॉर्म 10 एवं 11 (पश्चिम टर्मिनल डेक)',
    type: 'platform',
    floor: 'Ground',
    x: 700,
    y: 480,
    isAccessible: true,
    description: 'West terminal platforms near EVK Sampath Road gate',
    descriptionTa: 'ஈ.வெ.கி சம்பத் சாலை வாயில் அருகிலுள்ள நடைமேடை 10 & 11',
  },

  // =========================================================================
  // Station 3: TBM (Tambaram)
  // All 8 Platforms Across 4 Island Decks with Elevated FOB & Lift Network
  // =========================================================================
  {
    stationId: 'TBM',
    nodeId: 'TBM_WEST_GATE',
    name: 'West Bus Stand Entrance',
    nameTa: 'மேற்கு பேருந்து நிலைய நுழைவு வாயில்',
    nameHi: 'पश्चिम बस स्टैंड प्रवेश द्वार',
    type: 'gate',
    floor: 'Ground',
    x: 60,
    y: 300,
    isAccessible: true,
    description: 'Primary western station entrance adjacent to Tambaram West Bus Terminus',
    descriptionTa: 'தாம்பரம் மேற்கு பேருந்து நிலையம் அருகிலுள்ள பிரதான நுழைவு வாயில்',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_EAST_GATE',
    name: 'GST Road East Entrance',
    nameTa: 'ஜி.எஸ்.டி சாலை கிழக்கு நுழைவு வாயில்',
    nameHi: 'जीएसटी रोड पूर्व प्रवेश द्वार',
    type: 'gate',
    floor: 'Ground',
    x: 740,
    y: 300,
    isAccessible: true,
    description: 'Eastern entrance facing Grand Southern Trunk (GST) Road & MEPZ',
    descriptionTa: 'ஜி.எஸ்.டி சாலை மற்றும் MEPZ நோக்கிய கிழக்கு நுழைவு வாயில்',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_WEST_RAMP',
    name: 'West Approach Ramp',
    nameTa: 'மேற்கு அணுகு சாய்வுதளம்',
    nameHi: 'पश्चिम एप्रोच रैंप',
    type: 'ramp',
    floor: 'Ground',
    x: 130,
    y: 240,
    isAccessible: true,
    description: 'Long accessible incline ramp providing step-free ascent to elevated FOB Deck',
    descriptionTa: 'நடைமேம்பாலத்திற்கு செல்லும் மாற்றுத்திறனாளி சாய்வுதளப் பாதை',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_WEST_STAIRS',
    name: 'West Entry Stairs',
    nameTa: 'மேற்கு நுழைவு படிக்கட்டுகள்',
    nameHi: 'पश्चिम प्रवेश सीढ़ियाँ',
    type: 'stairs',
    floor: 'Ground',
    x: 130,
    y: 360,
    isAccessible: false,
    description: 'Entry staircase ascending from bus stand concourse to FOB Deck',
    descriptionTa: 'பேருந்து நிலையத்திலிருந்து நடைமேம்பாலத்திற்கு ஏறும் படிக்கட்டுகள்',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_RESTROOM',
    name: 'Divyangjan Restroom (West Concourse)',
    nameTa: 'மாற்றுத்திறனாளிகள் கழிப்பறை (மேற்கு அரங்கம்)',
    nameHi: 'दिव्यांगजन शौचालय (पश्चिम कॉनकोर्स)',
    type: 'restroom',
    floor: 'Ground',
    x: 100,
    y: 180,
    isAccessible: true,
    description: 'Wheelchair-accessible restroom facility located near West booking office',
    descriptionTa: 'மேற்கு பயணச்சீட்டு அலுவலகம் அருகிலுள்ள மாற்றுத்திறனாளி கழிப்பறை',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_FOB_1',
    name: 'Central FOB Deck (Bay 1)',
    nameTa: 'மத்திய நடைமேம்பாலம் (பகுதி 1)',
    nameHi: 'सेंट्रल एफओबी डेक (बे 1)',
    type: 'fob',
    floor: 'Level 1',
    x: 220,
    y: 300,
    isAccessible: true,
    description: 'Spine FOB deck above Platforms 1 & 2',
    descriptionTa: 'நடைமேடைகள் 1 & 2-க்கு மேலுள்ள நடைமேம்பாலப் பகுதி',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_FOB_2',
    name: 'Central FOB Deck (Bay 2)',
    nameTa: 'மத்திய நடைமேம்பாலம் (பகுதி 2)',
    nameHi: 'सेंट्रल एफओबी डेक (बे 2)',
    type: 'fob',
    floor: 'Level 1',
    x: 360,
    y: 300,
    isAccessible: true,
    description: 'Spine FOB deck above Platforms 3 & 4',
    descriptionTa: 'நடைமேடைகள் 3 & 4-க்கு மேலுள்ள நடைமேம்பாலப் பகுதி',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_FOB_3',
    name: 'Central FOB Deck (Bay 3)',
    nameTa: 'மத்திய நடைமேம்பாலம் (பகுதி 3)',
    nameHi: 'सेंट्रल एफओबी डेक (बे 3)',
    type: 'fob',
    floor: 'Level 1',
    x: 500,
    y: 300,
    isAccessible: true,
    description: 'Spine FOB deck above Platforms 5 & 6',
    descriptionTa: 'நடைமேடைகள் 5 & 6-க்கு மேலுள்ள நடைமேம்பாலப் பகுதி',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_FOB_4',
    name: 'Central FOB Deck (Bay 4)',
    nameTa: 'மத்திய நடைமேம்பாலம் (பகுதி 4)',
    nameHi: 'सेंट्रल एफओबी डेक (बे 4)',
    type: 'fob',
    floor: 'Level 1',
    x: 640,
    y: 300,
    isAccessible: true,
    description: 'Spine FOB deck above Platforms 7 & 8',
    descriptionTa: 'நடைமேடைகள் 7 & 8-க்கு மேலுள்ள நடைமேம்பாலப் பகுதி',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P1_2_LIFT',
    name: 'Platform 1 & 2 Lift Bay',
    nameTa: 'நடைமேடை 1 & 2 மின்தூக்கி',
    nameHi: 'प्लेटफॉर्म 1 एवं 2 लिफ्ट बे',
    type: 'lift',
    floor: 'Level 1',
    x: 220,
    y: 220,
    isAccessible: true,
    description: 'Elevator providing step-free descent to Platform 1 & 2 island deck',
    descriptionTa: 'நடைமேடை 1 & 2-க்கு இறங்கும் மின்தூக்கி',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P1_2_STAIRS',
    name: 'Platform 1 & 2 Stairs',
    nameTa: 'நடைமேடை 1 & 2 படிக்கட்டுகள்',
    nameHi: 'प्लेटफॉर्म 1 एवं 2 सीढ़ियाँ',
    type: 'stairs',
    floor: 'Level 1',
    x: 220,
    y: 380,
    isAccessible: false,
    description: 'Flight staircase from FOB deck to Platform 1 & 2',
    descriptionTa: 'நடைமேம்பாலத்திலிருந்து நடைமேடை 1 & 2-க்கு இறங்கும் படிக்கட்டுகள்',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P1_2',
    name: 'Platform 1 & 2 (Beach Suburban)',
    nameTa: 'நடைமேடை 1 & 2 (கடற்கரை மின்சார ரயில்)',
    nameHi: 'प्लेटफॉर्म 1 एवं 2 (बीच उपनगरीय)',
    type: 'platform',
    floor: 'Ground',
    x: 220,
    y: 460,
    isAccessible: true,
    description: 'Dedicated suburban island platform serving high-frequency Beach EMU locals',
    descriptionTa: 'சென்னை கடற்கரை மின்சார ரயில்களுக்கான நடைமேடை 1 & 2',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P3_4_LIFT',
    name: 'Platform 3 & 4 Lift Bay',
    nameTa: 'நடைமேடை 3 & 4 மின்தூக்கி',
    nameHi: 'प्लेटफॉर्म 3 एवं 4 लिफ्ट बे',
    type: 'lift',
    floor: 'Level 1',
    x: 360,
    y: 220,
    isAccessible: true,
    description: 'Elevator connecting FOB deck to Platform 3 & 4',
    descriptionTa: 'நடைமேம்பாலத்திலிருந்து நடைமேடை 3 & 4-க்கு செல்லும் மின்தூக்கி',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P3_4_STAIRS',
    name: 'Platform 3 & 4 Stairs',
    nameTa: 'நடைமேடை 3 & 4 படிக்கட்டுகள்',
    nameHi: 'प्लेटफॉर्म 3 एवं 4 सीढ़ियाँ',
    type: 'stairs',
    floor: 'Level 1',
    x: 360,
    y: 380,
    isAccessible: false,
    description: 'Flight staircase down to Platforms 3 & 4',
    descriptionTa: 'நடைமேடை 3 & 4-க்கு செல்லும் படிக்கட்டுகள்',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P3_4',
    name: 'Platform 3 & 4 (Chengalpattu Fast Line)',
    nameTa: 'நடைமேடை 3 & 4 (செங்கல்பட்டு விரைவு தடம்)',
    nameHi: 'प्लेटफॉर्म 3 एवं 4 (चेंगलपट्टु फास्ट लाइन)',
    type: 'platform',
    floor: 'Ground',
    x: 360,
    y: 460,
    isAccessible: true,
    description: 'Fast suburban and passenger line island platform towards Chengalpattu / Kanchipuram',
    descriptionTa: 'செங்கல்பட்டு மற்றும் காஞ்சிபுரம் ரயில்களுக்கான நடைமேடை 3 & 4',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P5_6_LIFT',
    name: 'Platform 5 & 6 Lift Bay',
    nameTa: 'நடைமேடை 5 & 6 மின்தூக்கி',
    nameHi: 'प्लेटफॉर्म 5 एवं 6 लिफ्ट बे',
    type: 'lift',
    floor: 'Level 1',
    x: 500,
    y: 220,
    isAccessible: true,
    description: 'Elevator connecting FOB deck to Platform 5 & 6 mainline deck',
    descriptionTa: 'நடைமேம்பாலத்திலிருந்து நடைமேடை 5 & 6-க்கு செல்லும் மின்தூக்கி',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P5_6_STAIRS',
    name: 'Platform 5 & 6 Stairs',
    nameTa: 'நடைமேடை 5 & 6 படிக்கட்டுகள்',
    nameHi: 'प्लेटफॉर्म 5 एवं 6 सीढ़ियाँ',
    type: 'stairs',
    floor: 'Level 1',
    x: 500,
    y: 380,
    isAccessible: false,
    description: 'Flight stairs to Platforms 5 & 6',
    descriptionTa: 'நடைமேடை 5 & 6-க்கு செல்லும் படிக்கட்டுகள்',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P5_6',
    name: 'Platform 5 & 6 (Mainline Express)',
    nameTa: 'நடைமேடை 5 & 6 (மெயின்லைன் விரைவு ரயில் தளம்)',
    nameHi: 'प्लेटफॉर्म 5 एवं 6 (मेनलाइन एक्सप्रेस)',
    type: 'platform',
    floor: 'Ground',
    x: 500,
    y: 460,
    isAccessible: true,
    description: 'Mainline island platform for southern express trains originating or halting at Tambaram',
    descriptionTa: 'தாம்பரம் முனைய விரைவு ரயில்களுக்கான நடைமேடை 5 & 6',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P7_8_LIFT',
    name: 'Platform 7 & 8 Lift Bay',
    nameTa: 'நடைமேடை 7 & 8 மின்தூக்கி',
    nameHi: 'प्लेटफॉर्म 7 एवं 8 लिफ्ट बे',
    type: 'lift',
    floor: 'Level 1',
    x: 640,
    y: 220,
    isAccessible: true,
    description: 'Elevator connecting FOB deck to Platform 7 & 8',
    descriptionTa: 'நடைமேம்பாலத்திலிருந்து நடைமேடை 7 & 8-க்கு செல்லும் மின்தூக்கி',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P7_8_STAIRS',
    name: 'Platform 7 & 8 Stairs',
    nameTa: 'நடைமேடை 7 & 8 படிக்கட்டுகள்',
    nameHi: 'प्लेटफॉर्म 7 एवं 8 सीढ़ियाँ',
    type: 'stairs',
    floor: 'Level 1',
    x: 640,
    y: 380,
    isAccessible: false,
    description: 'Flight stairs to Platforms 7 & 8',
    descriptionTa: 'நடைமேடை 7 & 8-க்கு செல்லும் படிக்கட்டுகள்',
  },
  {
    stationId: 'TBM',
    nodeId: 'TBM_P7_8',
    name: 'Platform 7 & 8 (Express / GST Side)',
    nameTa: 'நடைமேடை 7 & 8 (ஜி.எஸ்.டி சாலை விரைவு ரயில் தளம்)',
    nameHi: 'प्लेटफॉर्म 7 एवं 8 (एक्सप्रेस / जीएसटी साइड)',
    type: 'platform',
    floor: 'Ground',
    x: 640,
    y: 460,
    isAccessible: true,
    description: 'Easternmost island platform adjacent to GST Road for superfast express services',
    descriptionTa: 'ஜி.எஸ்.டி சாலை அருகிலுள்ள அதிவிரைவு ரயில்களுக்கான நடைமேடை 7 & 8',
  },
];

// Helper to generate bidirectional edge pairs
function createBidirectionalEdge(
  stationId,
  from,
  to,
  distance,
  flags = {},
  instructionEn = '',
  reverseEn = '',
  instructionTa = '',
  reverseTa = ''
) {
  return [
    {
      stationId,
      fromNode: from,
      toNode: to,
      distance,
      hasStairs: flags.hasStairs || false,
      hasElevator: flags.hasElevator || false,
      hasRamp: flags.hasRamp || false,
      isOperational: flags.isOperational !== undefined ? flags.isOperational : true,
      instruction: instructionEn || `Walk ${distance}m towards ${to}`,
      instructionTa: instructionTa || `${distance} மீட்டர் தூரம் நடந்து செல்லவும்`,
    },
    {
      stationId,
      fromNode: to,
      toNode: from,
      distance,
      hasStairs: flags.hasStairs || false,
      hasElevator: flags.hasElevator || false,
      hasRamp: flags.hasRamp || false,
      isOperational: flags.isOperational !== undefined ? flags.isOperational : true,
      instruction: reverseEn || `Walk ${distance}m back towards ${from}`,
      instructionTa: reverseTa || `${distance} மீட்டர் தூரம் திரும்பி நடக்கவும்`,
    },
  ];
}

const edgesData = [
  // =========================================================================
  // Station 1: MAS (Puratchi Thalaivar Dr. M.G.R. Central) Edges
  // =========================================================================
  ...createBidirectionalEdge('MAS', 'MAS_MAIN_GATE', 'MAS_CONCOURSE', 40, { hasStairs: false },
    'Walk through the heritage porch into the Grand Concourse',
    'Walk towards the main heritage clocktower exit',
    'பிரதான போர்டிகோ வழியாக மத்திய அரங்கத்திற்கு செல்லவும்',
    'பிரதான பாரம்பரிய வெளியேறும் வாயிலை நோக்கி செல்லவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_MMC_GATE', 'MAS_CONCOURSE', 55, { hasStairs: false },
    'Walk through the suburban connector into the Grand Concourse',
    'Walk north towards the Moore Market suburban terminal gate',
    'புறநகர் இணைப்பு பாதை வழியாக மத்திய அரங்கத்திற்கு செல்லவும்',
    'மூர் மார்க்கெட் புறநகர் முனைய வாயிலை நோக்கி செல்லவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_DIVYANG', 15, { hasStairs: false },
    'Walk towards the Divyangjan Special Assistance & Buggy Booth',
    'Return to the Grand Concourse from the Divyangjan Booth',
    'மாற்றுத்திறனாளிகள் உதவி மையம் மற்றும் பேட்டரி கார் பகுதிக்கு செல்லவும்',
    'உதவி மையத்திலிருந்து மத்திய அரங்கத்திற்கு திரும்பவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_P1', 70, { hasStairs: false },
    'Walk along the level ground concourse directly to Platform 1',
    'Walk from Platform 1 back into the Grand Concourse',
    'தரைதள அரங்கம் வழியாக நேரடியாக நடைமேடை 1-க்கு செல்லவும்',
    'நடைமேடை 1-லிருந்து மத்திய அரங்கத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_P2', 60, { hasStairs: false },
    'Walk along the buffer stops concourse to Platform 2',
    'Walk from Platform 2 buffer to the main concourse',
    'பஃபர் ஸ்டாப் பாதை வழியாக நடைமேடை 2-க்கு செல்லவும்',
    'நடைமேடை 2-லிருந்து மத்திய அரங்கத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_P3_4', 75, { hasStairs: false },
    'Walk along the concourse buffer walkway to Platforms 3 & 4',
    'Walk from Platforms 3 & 4 buffer into the concourse',
    'அரங்க நடைபாதை வழியாக நடைமேடை 3 & 4-க்கு செல்லவும்',
    'நடைமேடை 3 & 4-லிருந்து அரங்கத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_P5_6', 90, { hasStairs: false },
    'Walk along the concourse buffer walkway to Platforms 5 & 6',
    'Walk from Platforms 5 & 6 buffer into the concourse',
    'அரங்க நடைபாதை வழியாக நடைமேடை 5 & 6-க்கு செல்லவும்',
    'நடைமேடை 5 & 6-லிருந்து அரங்கத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_P7_8', 110, { hasStairs: false },
    'Walk along the concourse walkway to Platforms 7 & 8',
    'Walk from Platforms 7 & 8 buffer into the concourse',
    'அரங்க நடைபாதை வழியாக நடைமேடை 7 & 8-க்கு செல்லவும்',
    'நடைமேடை 7 & 8-லிருந்து அரங்கத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_P9_12', 130, { hasStairs: false },
    'Walk north along concourse buffer to Platforms 9 through 12',
    'Walk from Platforms 9-12 towards the main concourse',
    'வடக்கு அரங்கம் வழியாக நடைமேடைகள் 9 முதல் 12-க்கு செல்லவும்',
    'நடைமேடைகள் 9-12-லிருந்து பிரதான அரங்கத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_FOB_LIFT_MAIN', 35, { hasStairs: false },
    'Walk to Central FOB Lift A on the concourse',
    'Step out of Lift A onto the concourse',
    'அரங்கத்தில் உள்ள மத்திய நடைமேம்பால மின்தூக்கி A-க்கு செல்லவும்',
    'மின்தூக்கி A-லிருந்து அரங்கத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_CONCOURSE', 'MAS_FOB_STAIRS_MAIN', 25, { hasStairs: false },
    'Walk to the base of Central FOB stairs on the concourse',
    'Descend stairs to the concourse floor',
    'அரங்கத்தில் உள்ள மத்திய நடைமேம்பால படிக்கட்டுகளுக்கு செல்லவும்',
    'படிக்கட்டுகளிலிருந்து அரங்க தளத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_FOB_LIFT_MAIN', 'MAS_FOB_DECK', 40, { hasElevator: true, hasStairs: false },
    'Take Central Lift A up to Level 1 Foot Overbridge Deck',
    'Take Central Lift A down to the Ground Concourse',
    'மின்தூக்கி A வழியாக முதல் தள நடைமேம்பாலத்திற்கு மேலே செல்லவும்',
    'மின்தூக்கி A வழியாக தரைதள அரங்கத்திற்கு கீழே இறங்கவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_FOB_STAIRS_MAIN', 'MAS_FOB_DECK', 30, { hasStairs: true },
    'Climb stairs to the Level 1 Foot Overbridge Deck',
    'Descend stairs from FOB Deck to Ground Concourse',
    'படிக்கட்டுகள் வழியாக முதல் தள நடைமேம்பாலத்திற்கு ஏறவும்',
    'நடைமேம்பாலத்திலிருந்து தரைதளத்திற்கு படிக்கட்டுகளில் இறங்கவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_FOB_DECK', 'MAS_P2_LIFT', 20, { hasStairs: false },
    'Walk across FOB deck to the Platform 2 Lift Bay',
    'Step out of Platform 2 Lift onto the FOB deck',
    'நடைமேம்பாலம் வழியாக நடைமேடை 2 மின்தூக்கிக்கு செல்லவும்',
    'மின்தூக்கியிலிருந்து நடைமேம்பால தளத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_P2_LIFT', 'MAS_P2', 15, { hasElevator: true, hasStairs: false },
    'Take the elevator down to Platform 2 Boarding Deck',
    'Take the elevator up from Platform 2 to Level 1 FOB',
    'மின்தூக்கி மூலம் நடைமேடை 2 தளத்திற்கு கீழே இறங்கவும்',
    'மின்தூக்கி மூலம் நடைமேடை 2-லிருந்து முதல் தள நடைமேம்பாலத்திற்கு செல்லவும்'),

  ...createBidirectionalEdge('MAS', 'MAS_P2', 'MAS_P3_4', 30, { hasStairs: false },
    'Walk across the cross-platform concourse to Platforms 3 & 4',
    'Walk across to Platform 2',
    'நடைபாதை வழியாக நடைமேடை 3 & 4-க்கு செல்லவும்',
    'நடைமேடை 2-க்கு திரும்பி செல்லவும்'),

  // =========================================================================
  // Station 2: MS (Chennai Egmore) Edges
  // =========================================================================
  ...createBidirectionalEdge('MS', 'MS_GATE_1', 'MS_MAIN_HALL', 30, { hasStairs: false },
    'Walk through the east entrance into the Main Heritage Concourse',
    'Walk towards the Gandhi Irwin Road East Exit',
    'கிழக்கு வாயில் வழியாக பிரதான அரங்கத்திற்குள் செல்லவும்',
    'காந்தி இர்வின் சாலை வெளியேறும் வாயிலை நோக்கி செல்லவும்'),

  ...createBidirectionalEdge('MS', 'MS_MAIN_HALL', 'MS_DIVYANG_DESK', 15, { hasStairs: false },
    'Walk to the Divyangjan Special Assistance Booth',
    'Return to the central ticket concourse',
    'மாற்றுத்திறனாளிகள் சிறப்பு உதவி மையத்திற்கு செல்லவும்',
    'மத்திய பயணச்சீட்டு அரங்கத்திற்கு திரும்பவும்'),

  ...createBidirectionalEdge('MS', 'MS_MAIN_HALL', 'MS_P1', 30, { hasStairs: false },
    'Walk straight ahead onto Platform 1 (direct ground access)',
    'Walk from Platform 1 into the Main Concourse',
    'நேராக நடந்து நடைமேடை 1-க்கு செல்லவும் (நேரடி தரைதள வழி)',
    'நடைமேடை 1-லிருந்து பிரதான அரங்கத்திற்கு வரவும்'),

  ...createBidirectionalEdge('MS', 'MS_P1', 'MS_SUB_RAMP_P1', 35, { hasRamp: true, hasStairs: false },
    'Follow the accessible incline ramp down towards Central Subway',
    'Climb the ramp up to Platform 1',
    'சாய்வுதளம் வழியாக மத்திய சுரங்கப்பாதையை நோக்கி இறங்கவும்',
    'சாய்வுதளம் வழியாக நடைமேடை 1-க்கு மேலே ஏறவும்'),

  ...createBidirectionalEdge('MS', 'MS_P1', 'MS_SUB_STAIR_P1', 20, { hasStairs: true },
    'Take the stairs down into the subway tunnel',
    'Climb the stairs up to Platform 1',
    'படிக்கட்டுகள் வழியாக சுரங்க நடைபாதை தடத்தில் இறங்கவும்',
    'படிக்கட்டுகள் வழியாக நடைமேடை 1-க்கு ஏறவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_RAMP_P1', 'MS_SUB_TUNNEL_A', 30, { hasStairs: false },
    'Walk along the level subway tunnel passageway',
    'Walk back towards the Platform 1 subway ramp',
    'சுரங்கப்பாதை தடத்தில் நேராக செல்லவும்',
    'நடைமேடை 1 சாய்வுதளத்தை நோக்கி செல்லவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_STAIR_P1', 'MS_SUB_TUNNEL_A', 25, { hasStairs: false },
    'Walk along the subway corridor to the central junction',
    'Walk towards Platform 1 subway stairs',
    'சுரங்க நடைபாதை சந்திப்புக்கு செல்லவும்',
    'நடைமேடை 1 படிக்கட்டுகளுக்கு செல்லவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_TUNNEL_A', 'MS_P2_3', 35, { hasRamp: true, hasStairs: false },
    'Take the subway ramp up to Platform 2 & 3 Island Deck',
    'Descend the ramp from Platform 2 & 3 into the subway tunnel',
    'சாய்வுதளம் வழியாக நடைமேடை 2 & 3-க்கு மேலே ஏறவும்',
    'நடைமேடை 2 & 3-லிருந்து சுரங்கப்பாதைக்கு இறங்கவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_TUNNEL_A', 'MS_SUB_RAMP_P4', 25, { hasStairs: false },
    'Walk along the subway corridor to the Platform 4 & 5 ramp base',
    'Return to the central subway artery',
    'நடைமேடை 4 & 5 சாய்வுதள பகுதிக்கு செல்லவும்',
    'மத்திய சுரங்கப்பாதைக்கு திரும்பவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_RAMP_P4', 'MS_P4_5', 35, { hasRamp: true, hasStairs: false },
    'Ascend the ramp up onto Platform 4 & 5 (Express line)',
    'Descend the ramp from Platform 4 & 5 into the subway tunnel',
    'சாய்வுதளம் வழியாக நடைமேடை 4 & 5-க்கு மேலே ஏறவும்',
    'நடைமேடை 4 & 5-லிருந்து சுரங்கப்பாதைக்கு இறங்கவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_TUNNEL_A', 'MS_SUB_STAIR_P4', 20, { hasStairs: false },
    'Walk to the base of Platform 4 & 5 subway stairs',
    'Return to the central subway corridor',
    'நடைமேடை 4 & 5 படிக்கட்டுகளுக்கு செல்லவும்',
    'மத்திய சுரங்க நடைபாதை தட்டத்திற்கு திரும்பவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_STAIR_P4', 'MS_P4_5', 25, { hasStairs: true },
    'Climb the stairs up onto Platform 4 & 5',
    'Descend the stairs from Platform 4 & 5 into the subway',
    'படிக்கட்டுகள் வழியாக நடைமேடை 4 & 5-க்கு மேலே ஏறவும்',
    'நடைமேடை 4 & 5-லிருந்து படிக்கட்டுகள் வழியாக சுரங்கப்பாதைக்கு இறங்கவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_TUNNEL_A', 'MS_P6_7', 45, { hasRamp: true, hasStairs: false },
    'Take the west subway ramp up onto Platform 6 & 7',
    'Descend from Platform 6 & 7 into the subway tunnel',
    'மேற்கு சுரங்க சாய்வுதளம் வழியாக நடைமேடை 6 & 7-க்கு ஏறவும்',
    'நடைமேடை 6 & 7-லிருந்து சுரங்கப்பாதைக்கு இறங்கவும்'),

  ...createBidirectionalEdge('MS', 'MS_SUB_TUNNEL_A', 'MS_P8_9', 55, { hasRamp: true, hasStairs: false },
    'Take the subway ramp up onto suburban Platform 8 & 9',
    'Descend from Platform 8 & 9 into the subway tunnel',
    'சுரங்க சாய்வுதளம் வழியாக மின்சார புறநகர் நடைமேடை 8 & 9-க்கு ஏறவும்',
    'நடைமேடை 8 & 9-லிருந்து சுரங்கப்பாதைக்கு இறங்கவும்'),

  ...createBidirectionalEdge('MS', 'MS_P8_9', 'MS_P10_11', 40, { hasStairs: false },
    'Walk across to Platform 10 & 11 terminal deck',
    'Walk from Platform 10 & 11 towards Platform 8 & 9',
    'நடைபாதை வழியாக நடைமேடை 10 & 11-க்கு செல்லவும்',
    'நடைமேடை 8 & 9 நோக்கி செல்லவும்'),

  ...createBidirectionalEdge('MS', 'MS_P10_11', 'MS_GATE_2', 50, { hasStairs: false },
    'Walk directly out through the EVK Sampath Road West Entrance',
    'Enter through the West Entrance towards Platform 10 & 11',
    'ஈ.வெ.கி சம்பத் சாலை மேற்கு வாயில் வழியாக வெளியேறவும்',
    'மேற்கு வாயில் வழியாக நடைமேடை 10 & 11 பகுதிக்கு நுழையவும்'),

  // =========================================================================
  // Station 3: TBM (Tambaram) Edges
  // All 8 Platforms Across 4 Island Decks with Level Walkways & Lifts
  // =========================================================================
  ...createBidirectionalEdge('TBM', 'TBM_WEST_GATE', 'TBM_RESTROOM', 20, { hasStairs: false },
    'Walk to the Divyangjan Accessible Restroom on the west concourse',
    'Return from the restroom towards the West Bus Stand Entrance',
    'மேற்கு அரங்கத்திலுள்ள மாற்றுத்திறனாளிகள் கழிப்பறைக்கு செல்லவும்',
    'கழிப்பறையிலிருந்து மேற்கு நுழைவு வாயிலை நோக்கி வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_WEST_GATE', 'TBM_WEST_RAMP', 35, { hasRamp: true, hasStairs: false },
    'Follow the level pathway to the base of the West Approach Ramp',
    'Walk off the ramp towards the West Bus Stand Entrance',
    'மேற்கு அணுகு சாய்வுதளத்தின் தொடக்கப் பகுதிக்கு செல்லவும்',
    'சாய்வுதளத்திலிருந்து இறங்கி மேற்கு பேருந்து நிலைய வாயிலுக்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_WEST_GATE', 'TBM_WEST_STAIRS', 25, { hasStairs: false },
    'Walk to the base of the West Entry Stairs',
    'Walk from the stairs to the West Entrance gate',
    'மேற்கு நுழைவு படிக்கட்டுகளின் தொடக்கத்திற்கு செல்லவும்',
    'படிக்கட்டுகளிலிருந்து மேற்கு நுழைவு வாயிலுக்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_WEST_RAMP', 'TBM_FOB_1', 65, { hasRamp: true, hasStairs: false },
    'Ascend the long gentle ramp up to Central FOB Deck (Bay 1)',
    'Descend the accessible ramp down towards West Bus Stand Entrance',
    'சாய்வுதளம் வழியாக முதல் தள மத்திய நடைமேம்பாலத்திற்கு (பகுதி 1) மேலே ஏறவும்',
    'சாய்வுதளம் வழியாக மேற்கு பேருந்து நிலைய வாயிலை நோக்கி கீழே இறங்கவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_WEST_STAIRS', 'TBM_FOB_1', 40, { hasStairs: true },
    'Climb the stairs up to Central FOB Deck (Bay 1)',
    'Descend the stairs from FOB Deck towards West Entrance',
    'படிக்கட்டுகள் வழியாக மத்திய நடைமேம்பாலத்திற்கு (பகுதி 1) ஏறவும்',
    'நடைமேம்பாலத்திலிருந்து மேற்கு வாயிலை நோக்கி படிக்கட்டுகளில் இறங்கவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_FOB_1', 'TBM_FOB_2', 35, { hasStairs: false },
    'Walk east along the elevated FOB spine to Bay 2',
    'Walk west along the FOB spine towards Bay 1',
    'நடைமேம்பாலத்தின் வழியாக கிழக்கு நோக்கி பகுதி 2-க்கு செல்லவும்',
    'நடைமேம்பாலத்தின் வழியாக மேற்கு நோக்கி பகுதி 1-க்கு செல்லவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_FOB_2', 'TBM_FOB_3', 35, { hasStairs: false },
    'Walk east along the elevated FOB spine to Bay 3',
    'Walk west along the FOB spine towards Bay 2',
    'நடைமேம்பாலத்தின் வழியாக கிழக்கு நோக்கி பகுதி 3-க்கு செல்லவும்',
    'நடைமேம்பாலத்தின் வழியாக மேற்கு நோக்கி பகுதி 2-க்கு செல்லவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_FOB_3', 'TBM_FOB_4', 35, { hasStairs: false },
    'Walk east along the elevated FOB spine to Bay 4',
    'Walk west along the FOB spine towards Bay 3',
    'நடைமேம்பாலத்தின் வழியாக கிழக்கு நோக்கி பகுதி 4-க்கு செல்லவும்',
    'நடைமேம்பாலத்தின் வழியாக மேற்கு நோக்கி பகுதி 3-க்கு செல்லவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_FOB_4', 'TBM_EAST_GATE', 40, { hasStairs: false },
    'Walk to the GST Road East Entrance connector',
    'Walk from the East Entrance onto the FOB Deck',
    'ஜி.எஸ்.டி சாலை கிழக்கு நுழைவு வாயில் பகுதிக்கு செல்லவும்',
    'கிழக்கு வாயிலிலிருந்து நடைமேம்பாலத்திற்கு செல்லவும்'),

  // Platforms 1 & 2 Lift & Stairs from FOB Bay 1
  ...createBidirectionalEdge('TBM', 'TBM_FOB_1', 'TBM_P1_2_LIFT', 15, { hasStairs: false },
    'Walk to Platform 1 & 2 Lift Bay on the FOB deck',
    'Step out of the lift onto FOB Bay 1',
    'நடைமேம்பாலத்தில் உள்ள நடைமேடை 1 & 2 மின்தூக்கிக்கு செல்லவும்',
    'மின்தூக்கியிலிருந்து நடைமேம்பால பகுதி 1-க்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_P1_2_LIFT', 'TBM_P1_2', 15, { hasElevator: true, hasStairs: false },
    'Take the lift down to Platform 1 & 2 (Beach Suburban)',
    'Take the lift up from Platform 1 & 2 to Level 1 FOB',
    'மின்தூக்கி மூலம் நடைமேடை 1 & 2 (கடற்கரை மின்சார ரயில்) தளத்திற்கு இறங்கவும்',
    'மின்தூக்கி மூலம் நடைமேடை 1 & 2-லிருந்து முதல் தள நடைமேம்பாலத்திற்கு செல்லவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_FOB_1', 'TBM_P1_2_STAIRS', 18, { hasStairs: false },
    'Walk to the head of Platform 1 & 2 stairs on the FOB deck',
    'Step off Platform 1 & 2 stairs onto the FOB deck',
    'நடைமேடை 1 & 2 படிக்கட்டுகளின் தொடக்கத்திற்கு செல்லவும்',
    'படிக்கட்டுகளிலிருந்து நடைமேம்பாலத்திற்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_P1_2_STAIRS', 'TBM_P1_2', 20, { hasStairs: true },
    'Descend the staircase to Platform 1 & 2',
    'Climb the staircase from Platform 1 & 2 to FOB Level 1',
    'படிக்கட்டுகள் வழியாக நடைமேடை 1 & 2 தளத்திற்கு இறங்கவும்',
    'நடைமேடை 1 & 2-லிருந்து படிக்கட்டுகள் வழியாக முதல் தள நடைமேம்பாலத்திற்கு ஏறவும்'),

  // Platforms 3 & 4 Lift & Stairs from FOB Bay 2
  ...createBidirectionalEdge('TBM', 'TBM_FOB_2', 'TBM_P3_4_LIFT', 15, { hasStairs: false },
    'Walk to Platform 3 & 4 Lift Bay on the FOB deck',
    'Step out of the lift onto FOB Bay 2',
    'நடைமேம்பாலத்தில் உள்ள நடைமேடை 3 & 4 மின்தூக்கிக்கு செல்லவும்',
    'மின்தூக்கியிலிருந்து நடைமேம்பால பகுதி 2-க்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_P3_4_LIFT', 'TBM_P3_4', 15, { hasElevator: true, hasStairs: false },
    'Take the lift down to Platform 3 & 4 (Chengalpattu Fast Line)',
    'Take the lift up from Platform 3 & 4 to Level 1 FOB',
    'மின்தூக்கி மூலம் நடைமேடை 3 & 4 (செங்கல்பட்டு விரைவு தடம்) தளத்திற்கு இறங்கவும்',
    'மின்தூக்கி மூலம் நடைமேடை 3 & 4-லிருந்து முதல் தள நடைமேம்பாலத்திற்கு செல்லவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_FOB_2', 'TBM_P3_4_STAIRS', 18, { hasStairs: false },
    'Walk to Platform 3 & 4 stairs on the FOB deck',
    'Step off Platform 3 & 4 stairs onto the FOB deck',
    'நடைமேடை 3 & 4 படிக்கட்டுகளுக்கு செல்லவும்',
    'படிக்கட்டுகளிலிருந்து நடைமேம்பாலத்திற்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_P3_4_STAIRS', 'TBM_P3_4', 20, { hasStairs: true },
    'Descend the stairs to Platform 3 & 4',
    'Climb the stairs from Platform 3 & 4 to FOB Level 1',
    'படிக்கட்டுகள் வழியாக நடைமேடை 3 & 4-க்கு இறங்கவும்',
    'நடைமேடை 3 & 4-லிருந்து படிக்கட்டுகள் வழியாக முதல் தளத்திற்கு ஏறவும்'),

  // Platforms 5 & 6 Lift & Stairs from FOB Bay 3
  ...createBidirectionalEdge('TBM', 'TBM_FOB_3', 'TBM_P5_6_LIFT', 15, { hasStairs: false },
    'Walk to Platform 5 & 6 Lift Bay on the FOB deck',
    'Step out of the lift onto FOB Bay 3',
    'நடைமேம்பாலத்தில் உள்ள நடைமேடை 5 & 6 மின்தூக்கிக்கு செல்லவும்',
    'மின்தூக்கியிலிருந்து நடைமேம்பால பகுதி 3-க்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_P5_6_LIFT', 'TBM_P5_6', 15, { hasElevator: true, hasStairs: false },
    'Take the lift down to Platform 5 & 6 (Mainline Express)',
    'Take the lift up from Platform 5 & 6 to Level 1 FOB',
    'மின்தூக்கி மூலம் நடைமேடை 5 & 6 (மெயின்லைன் விரைவு ரயில்) தளத்திற்கு இறங்கவும்',
    'மின்தூக்கி மூலம் நடைமேடை 5 & 6-லிருந்து முதல் தள நடைமேம்பாலத்திற்கு செல்லவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_FOB_3', 'TBM_P5_6_STAIRS', 18, { hasStairs: false },
    'Walk to Platform 5 & 6 stairs on the FOB deck',
    'Step off Platform 5 & 6 stairs onto the FOB deck',
    'நடைமேடை 5 & 6 படிக்கட்டுகளுக்கு செல்லவும்',
    'படிக்கட்டுகளிலிருந்து நடைமேம்பாலத்திற்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_P5_6_STAIRS', 'TBM_P5_6', 20, { hasStairs: true },
    'Descend the stairs to Platform 5 & 6',
    'Climb the stairs from Platform 5 & 6 to FOB Level 1',
    'படிக்கட்டுகள் வழியாக நடைமேடை 5 & 6-க்கு இறங்கவும்',
    'நடைமேடை 5 & 6-லிருந்து படிக்கட்டுகள் வழியாக முதல் தளத்திற்கு ஏறவும்'),

  // Platforms 7 & 8 Lift & Stairs from FOB Bay 4
  ...createBidirectionalEdge('TBM', 'TBM_FOB_4', 'TBM_P7_8_LIFT', 15, { hasStairs: false },
    'Walk to Platform 7 & 8 Lift Bay on the FOB deck',
    'Step out of the lift onto FOB Bay 4',
    'நடைமேம்பாலத்தில் உள்ள நடைமேடை 7 & 8 மின்தூக்கிக்கு செல்லவும்',
    'மின்தூக்கியிலிருந்து நடைமேம்பால பகுதி 4-க்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_P7_8_LIFT', 'TBM_P7_8', 15, { hasElevator: true, hasStairs: false },
    'Take the lift down to Platform 7 & 8 (Express / GST Side)',
    'Take the lift up from Platform 7 & 8 to Level 1 FOB',
    'மின்தூக்கி மூலம் நடைமேடை 7 & 8 (ஜி.எஸ்.டி சாலை விரைவு ரயில்) தளத்திற்கு இறங்கவும்',
    'மின்தூக்கி மூலம் நடைமேடை 7 & 8-லிருந்து முதல் தள நடைமேம்பாலத்திற்கு செல்லவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_FOB_4', 'TBM_P7_8_STAIRS', 18, { hasStairs: false },
    'Walk to Platform 7 & 8 stairs on the FOB deck',
    'Step off Platform 7 & 8 stairs onto the FOB deck',
    'நடைமேடை 7 & 8 படிக்கட்டுகளுக்கு செல்லவும்',
    'படிக்கட்டுகளிலிருந்து நடைமேம்பாலத்திற்கு வரவும்'),

  ...createBidirectionalEdge('TBM', 'TBM_P7_8_STAIRS', 'TBM_P7_8', 20, { hasStairs: true },
    'Descend the stairs to Platform 7 & 8',
    'Climb the stairs from Platform 7 & 8 to FOB Level 1',
    'படிக்கட்டுகள் வழியாக நடைமேடை 7 & 8-க்கு இறங்கவும்',
    'நடைமேடை 7 & 8-லிருந்து படிக்கட்டுகள் வழியாக முதல் தளத்திற்கு ஏறவும்'),
];

async function seedDatabase() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB successfully.');

    // Clear existing collections
    console.log('Clearing existing Station, Node, and Edge collections...');
    await Station.deleteMany({});
    await Node.deleteMany({});
    await Edge.deleteMany({});
    console.log('Existing collections cleared.');

    // Insert Stations
    console.log(`Inserting ${stationsData.length} stations...`);
    const insertedStations = await Station.insertMany(stationsData);
    console.log(`Inserted ${insertedStations.length} stations successfully.`);

    // Insert Nodes
    console.log(`Inserting ${nodesData.length} nodes...`);
    const insertedNodes = await Node.insertMany(nodesData);
    console.log(`Inserted ${insertedNodes.length} nodes successfully.`);

    // Insert Edges
    console.log(`Inserting ${edgesData.length} edges...`);
    const insertedEdges = await Edge.insertMany(edgesData);
    console.log(`Inserted ${insertedEdges.length} edges successfully.`);

    console.log('\n--- SEED SUMMARY ---');
    console.log(`Stations: ${insertedStations.length}`);
    console.log(`Nodes:    ${insertedNodes.length}`);
    console.log(`Edges:    ${insertedEdges.length}`);
    console.log('Ground truth Chennai RailNav database seeding completed successfully!');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();
